[build]
release = true

[watch]
ignore = [".idea"]

[serve]
addresses = ["127.0.0.1"]
port = 52784

[[hooks]]
stage = "post_build"
command = "cargo"
command_arguments = ["run", "--bin", "copy-and-link"]
